title: Ge Zhang
logo: profile.jpeg
description: PhD Candidate<br> School of Computing, Macquarie University<br>Email: ge.zhang5@students.mq.edu.au<br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
github:
  is_project_page: false
